### ISSUE TITLE
Using placeholders for cloudwatch out

### ISSUE THREAD

**Issue by ndench** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#126]
The readme says that you can use placeholders such as `%{uuid}` and `%{hostname}` but they aren't working when I'm putting them as my `log_stream_name` - the log stream is the literal string `"%{hostname}"`.

Looking at the [PR that introduced them](https://github.com/fluent-plugins-nursery/fluent-plugin-cloudwatch-logs/pull/34) and the current [out_cloudwatch_logs.rb](https://github.com/fluent-plugins-nursery/fluent-plugin-cloudwatch-logs/blob/d165d96bf88ce38eb3aaf13a5d25776b24a52812/lib/fluent/plugin/out_cloudwatch_logs.rb) in master, it appears that the `Fluent::Mixin::ConfigPlaceholders` has been removed.

Is there something I'm missing to get this work?

**Comment by cosmo0920** [comment]
Hmm..., README is outdated.
In v1, `Fluent::Mixin::ConfigPlaceholders` does not work.
PR https://github.com/fluent-plugins-nursery/fluent-plugin-cloudwatch-logs/pull/109 tries to add placeholders but it does not write tests for them.

**Comment by ndench** [comment]
Ah fair enough. I've managed to work around the problem for now by setting environment variables in `/etc/default/td-agent` on boot and using them in fluentd conf.
