### ISSUE TITLE
RejectedLogEventsInfo warning not helpful

### ISSUE THREAD

**Issue by pappnase99** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#135]
#### Problem
Because of an unexpected behavior in the fluentd filter_parser plugin the timestamp property of my log events got deleted. This means the log event has no valid timestamp and will be discarded by Cloudwatch Logs. Unfortunately we only see a warning message like this one in the fluentd log:

`2018-12-12 15:35:57 +0000 [warn]: #0 #<struct Aws::CloudWatchLogs::Types::RejectedLogEventsInfo too_new_log_event_start_index=nil, too_old_log_event_end_index=3, expired_log_event_end_index=nil>`

To me this is really not helpful. We don't see the rejected log message so it's difficult to pinpoint the source of these messages and to understand that there is a timestamp issue at all. Furthermore, log events disappearing is a serious issue instead of a simple warning.

#### Steps to replicate

```
<source>
  @type tail
  enable_stat_watcher false
  path /var/log/containers/*.log
  pos_file /var/log/fluentd-containers.log.pos
  time_format %Y-%m-%dT%H:%M:%S.%NZ
  tag kubernetes.*
  format json
  read_from_head true
</source>

# unexpected timestamp filtering
<filter kubernetes.var.log.containers.**.log>
  @type parser
  key_name log
  reserve_data true
  remove_key_name_field true
  inject_key_prefix log.
  <parse>
    @type json
  </parse>
</filter>

<match **>
  type cloudwatch_logs
  log_group_name "#{ENV['LOG_GROUP_NAME']}"
  auto_create_stream true
  use_tag_as_stream true
</match>
```

#### Expected Behavior or What you need to ask

- Print out the complete log event that got rejected.
- Explain the "too old" issue in human-readable terms.

#### Using Fluentd and CloudWatchLogs plugin versions

* Kubernetes
* Fluentd docker image fluent/fluentd-kubernetes-daemonset:v1.3.0-debian-cloudwatch
* Dependent gem versions
fluent-plugin-cloudwatch-logs version '0.6.1'
fluent-plugin-kubernetes_metadata_filter version '2.1.4'
fluent-plugin-rewrite-tag-filter version '2.1.0'
fluent-plugin-systemd version '1.0.1'
fluentd version '1.3.0'

**Comment by vsk-123** [comment]
Yes, I am getting the same error for that .
Anyone can advice on that ?

**Comment by cosmo0920** [comment]
Try https://github.com/fluent-plugins-nursery/fluent-plugin-cloudwatch-logs/pull/139.

**Comment by vsk-123** [comment]
Today We tried again with Fluentd docker image fluent/fluentd-kubernetes-daemonset:v1.3.0-debian-cloudwatch version but still i am getting same error.

Anyone can advice on that ?

**Comment by cosmo0920** [comment]
Current implementation throws away entire information except for the following:

```
2018-12-12 15:35:57 +0000 [warn]: #0 #<struct Aws::CloudWatchLogs::Types::RejectedLogEventsInfo too_new_log_event_start_index=nil, too_old_log_event_end_index=3, expired_log_event_end_index=nil>
```

This is limitation of current implementation:
https://github.com/fluent-plugins-nursery/fluent-plugin-cloudwatch-logs/blob/master/lib/fluent/plugin/out_cloudwatch_logs.rb#L330

If you raise log_level to debug, you can obtain information which includes request contents:

```aconf
@log_level debug
```

**Comment by cosmo0920** [comment]
i've released v0.7.2 which is added `log_rejected_request` parameter to dump request information.
Could you try v0.7.2?

**Comment by pappnase99** [comment]
Sounds great, could you open a PR here so the version gets updated?
https://github.com/fluent/fluentd-kubernetes-daemonset

**Comment by cosmo0920** [comment]
This issue seems to be solved.
Closing.
