### ISSUE TITLE
Request for a new release/tag

### ISSUE THREAD

**Issue by gregoryguillou** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#153]
Hello, 

Thank you for your plugin that is super useful! I was wondering if you would mind creating a new release/tag. The last one (v0.7.3) is from January and, some features, including one very useful to collect logs for EKS/Lambda with the right time is only on master. Thank you again.

Gregory

**Comment by GAHila** [comment]
@okkez @cosmo0920  any plans on creating a new release please?

**Comment by cosmo0920** [comment]
Thank you for notifying it and sorry for being late.
I've released v0.7.4 today.

**Comment by gregoryguillou** [comment]
Thank you @cosmo0920
