### ISSUE TITLE
Running td-agent on ec2 instance 

### ISSUE THREAD

**Issue by pandeyrahulgwl** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#165]
#### Problem
I am unable to run td-agent service on my ec2 instance to read logs from my containers and push them to cloud watch. 

I have already posted the issue with aws support, but doesn't worked for me. 
Problem is when I am editing the td-agent. Conf file according to my requirements I couldn't able to restart the service. 

Sorry to say but i cant share logs and journalctl -xe output. 

I have tried through many links and official documentation as well. 

Can anyone suggest some other useful links, will be helpful. 

Thanks
...

#### Steps to replicate

Provide example config and message

#### Expected Behavior or What you need to ask

...

#### Using Fluentd and CloudWatchLogs plugin versions

* OS version
* Bare Metal or within Docker or Kubernetes or others?
* Fluentd v0.12 or v0.14/v1.0
  * paste result of ``fluentd --version`` or ``td-agent --version``
* Dependent gem versions
  * paste boot log of fluentd or td-agent
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock

**Comment by cosmo0920** [comment]
Incomplete and no response issue.
Closing.
