### ISSUE TITLE
deprecation warnin in fluentd 1.8.1

### ISSUE THREAD

**Issue by markuman** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#171]
#### Problem

We see hundrets of deprecation warnings per minute

```
#1 Deprecated method: this method is going to be deleted. Use Fluent::MessagePackFactory.msgpack_packer
```

So we guess it's related to this output plugin, because we use mainly cloudwatch logs as output. But it's just a guess.

#### Steps to replicate

deploy fluent-plugin-cloudwatch-logs 0.7.6 with fluentd 1.8.1

**Comment by juhtie01** [comment]
We see the same.

**Comment by JustinPlute** [comment]
Also happening for me too.
