### ISSUE TITLE
How to get logs for a specific range?

### ISSUE THREAD

**Issue by gcavalcante8808** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#173]
#### Problem

I'd like to get logs from a specific date range (startTime, endTime) and send to an fluentd output.

#### Steps to replicate

N/A

#### Expected Behavior or What you need to ask

N/A

#### Using Fluentd and CloudWatchLogs plugin versions

I'm using kubernetes with the image "gcr.io/google-containers/fluentd-elasticsearch:v2.4.0" and 
"fluent-plugin-cloudwatch-logs" installed

**Comment by cosmo0920** [comment]
Currently, no way to handle it.

**Comment by cosmo0920** [comment]
I think that this use case should be implemented with [Embulk](https://www.embulk.org/) plugin and output file or something then, Fluentd tailing it.

**Comment by cosmo0920** [comment]
I'd reconsidered about this.
This feature request is reasonable for me but, in the future, we should provide CloudWatchLogs plugin for Embulk which is able to specify time range drain logs on CloudWatchLogs.
