### ISSUE TITLE
AWS SDK logging is present regardless of plugin log level

### ISSUE THREAD

**Issue by jacknagel** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#175]
### Problem

No matter what one sets as the plugin log level, all of the logging inside the SDK is logged at that level as well. This includes every API call - every PutLogEvents is logged to the fluentd stdout.

#162 enabled logging in the AWS SDK, and configured it to use the plugin's log level. However, the SDK's `log_level` parameter does not tell the SDK to only log messages at that level or greater, but rather _to log ALL of its messages at that level_.

Documentation: https://docs.aws.amazon.com/sdk-for-ruby/v2/api/Aws/CloudWatch/Client.html
> :log_level (Symbol) — default: :info — The log level to send messages to the logger at. See Plugins::Logging for more details.

Code: https://github.com/aws/aws-sdk-ruby/blob/97b28ccf18558fc908fd56f52741cf3329de9869/gems/aws-sdk-core/lib/aws-sdk-core/plugins/logging.rb#L50-L52
```ruby
def log(config, response)
  config.logger.send(config.log_level, format(config, response))
end
```

### Expected behavior

I should be able to set the plugin log level to a reasonable value like `:info` or `:warn` and not see this noise from the AWS SDK.

I think a good value for the SDK's `log_level` parameter is `:debug`, as it is not something one would normally want turned on in a production environment.

Of course, I would also be happy if this behavior was simply reverted.

**Comment by cosmo0920** [comment]
Oh, you are right.
I didn't notice about it.
I'd fixed this behavior in #177.
