### ISSUE TITLE
Support format in out_cloudwatch_logs

### ISSUE THREAD

**Issue by xiaohuangji** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#212]
#### Problem

The format is not recognized in out_cloudwatch_logs. Is there a common case to format output before sending to cloudwatch? 

logs in cloudwatch:  **"message":"Plain logs"**
expected only keep value(single_value format):   **"Plain logs"**

...

#### Steps to replicate

Provide example config and message

#### Expected Behavior or What you need to ask

...

#### Using Fluentd and CloudWatchLogs plugin versions

* OS version
* Bare Metal or within Docker or Kubernetes or others?
* Fluentd v0.12 or v0.14/v1.0
  * paste result of ``fluentd --version`` or ``td-agent --version``
* Dependent gem versions
  * paste boot log of fluentd or td-agent
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock

**Comment by cosmo0920** [comment]
We didn't support arbitrary format on out_cloudwatch_logs just supported JSON encoded style.
I've heard it for the first time.

**Comment by cosmo0920** [comment]
fluent-plugin-cloudwatch-logs v0.12.0 can handle `<format>` section on its configuration:

```aconf
<match **>
  @type cloudwatch_logs
  # ... Some stuff
  <format>
    @type single_value
    message_key message
  </format>
</match>
```
