### ISSUE TITLE
define logstream_name with a dynamic value from record

### ISSUE THREAD

**Issue by imedaouidene** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#244]
#### Problem
I'm trying to configure fluentd so that it creats a new logstream for each namespace. log_stream_name does not parse the value of the variable ${record['kubernetes‘]['namespace_name']}.

The logstream is created with this exact name : ${record['kubernetes‘]['namespace_name']}....

#### Steps to replicate

 <source>
      @type forward
      port 24224
</source>
<match kubernetes.**>
      @type cloudwatch_logs
      log_group_name my-log-group-sample
      log_stream_name ${record['kubernetes‘]['namespace_name']}
      auto_create_stream true
    
</match>
    
    
#### Expected Behavior or What you need to ask
name of kubernetes namespace
...

**Comment by wilkinho** [comment]
@imedaouidene I met the same problem, may I know how did you fix it? Thank you very much.

**Comment by wilkinho** [comment]
using `log_stream_name_key` fixed my issue.
