### ISSUE TITLE
few confirmations

### ISSUE THREAD

**Issue by iamhasibrahman** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#40]
Which data points are sent to cloudwatch? 

I see you support proxy, great news for us~

**Comment by cosmo0920** [comment]
If you specify `message_keys`, this plugin sends specified keys info CloudwatchLlogs.

```
message_keys key1,key3
```
```
{"key1":"value1", "key2":"value2", "key3":"value3} #=> send {"key1":"value1", "key3":"value3}
```

If nothing to be specified in `message_keys`, entire record is sent CloudwatchLogs.
