### ISSUE TITLE
setting AWS credentials

### ISSUE THREAD

**Issue by iamhasibrahman** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#41]
I would assume we will have fluentd conf setup as below - 

<match **>
  type kinesis
  stream_name FluentDHeartbeat
  aws_key_id 
  aws_sec_key 
  region ap-southeast-2
  random_partition_key true
  flush_interval 5s
  num_threads 1
</match>

Why then you would need this --

$ export AWS_REGION=us-east-1
$ export AWS_ACCESS_KEY_ID="YOUR_ACCESS_KEY"
$ export AWS_SECRET_ACCESS_KEY="YOUR_SECRET_ACCESS_KEY"

**Comment by ashlineldridge** [comment]
It should be possible for the plugin to pick up AWS credentials via an Instance Profile if it is running on an EC2 instance.

**Comment by rodlogic** [comment]
With my crude ruby-fu, something along these lines should do:
```
      if @aws_key_id && @aws_sec_key
        options[:credentials] = Aws::Credentials.new(@aws_key_id, @aws_sec_key)
        options[:region] = @region if @region
        options[:http_proxy] = @http_proxy if @http_proxy
      else
        options[:credentials] = Aws::InstanceProfileCredentials.new()
      end
```

**Comment by sampointer** [comment]
See the README amendments on my recent PR: https://github.com/ryotarai/fluent-plugin-cloudwatch-logs/pull/56/files

It would be great it this PR and the other outstanding ones were merged!

**Comment by BlackBsd** [comment]
I am still wondering how to fix this.

I am actually running this container in Kubernetes and I have the bashed into the container and can see the environment variables set:
$ env | grep AWS                                                                                                                                                                                                                 
   AWS_SECRET_ACCESS_KEY=....
   AWS_REGION=us-east-1
   AWS_ACCESS_KEY_ID=....

Even with them set i am still seeing this error:
2018-06-22 23:19:51 +0000 [error]: #0 unexpected error error_class=Aws::Errors::MissingRegionError error="missing region; use :region option or export region name to ENV['AWS_REGION']"

my fluentd.conf looks like:

<match **>
  @type cloudwatch_logs
  @id out_cloudwatch_logs
  log_group_name "#{ENV['LOG_GROUP_NAME']}"
  auto_create_stream true
  use_tag_as_stream true
</match>

Any ideas how to have the code running on and ec2 instance to just assume those roles?

**Comment by ndench** [comment]
I was unable to get it working with environment variables but it did work by setting it in the fluentd.conf:

```
aws_key_id KEY_ID
aws_sec_key SECRET_KEY
```

But the recommended way is to use IAM profiles, so I ended up switching to that. You have to create the role and set it in your fluentd.conf:

```
aws_use_sts true
aws_sts_role_arn ROLE_ARN
```

So either of those should work for you.
