### ISSUE TITLE
Wildcard for streams

### ISSUE THREAD

**Issue by Vehyla** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#44]
We are trying to pull in vpcflow logs from cloudwatch which lists about 100 eni interfaces.  I tried several forms of wildcarding but always end up with an error.

1 validation error detected: Value '[^:_]_>' at 'logStreamName' failed to satisfy constraint: Member must satisfy regular expression pattern: [^:_]_>

Is there possibly a way I can just pull in any stream in the existing log_group_name?

**Comment by nunofernandes** [comment]
+1

**Comment by cosmo0920** [comment]
It seems that it is prohibited by AWS Client API.
```
~/GitHub/fluent-plugin-cloudwatch-logs/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.20.1/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': 1 validation error detected: Value '**' at 'logStreamNamePrefix' failed to satisfy constraint: Member must satisfy regular expression pattern: [^:*]* (Aws::CloudWatchLogs::Errors::InvalidParameterException)
2018-11-30 13:35:01 +0900 [error]: #0 unexpected error error_class=Aws::CloudWatchLogs::Errors::InvalidParameterException error="1 validation error detected: Value '**' at 'logStreamNamePrefix' failed to satisfy constraint: Member must satisfy regular expression pattern: [^:*]*"
```

There is no way to pull any stream by specifying wildcards. :/
