### ISSUE TITLE
Doesn't work with >50 log groups in account

### ISSUE THREAD

**Issue by adamchainz** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#48]
The implementation of `log_group_exists?` calls `describe_log_groups` but doesn't paginate through all of them, it only uses the first page of results (see [AWS SDK docs](https://docs.aws.amazon.com/sdkforruby/api/Aws/CloudWatchLogs/Client.html#describe_log_groups-instance_method)). Therefore it isn't a true test of whether the group exists.

**Comment by GeorgiMateev** [comment]
Is this issue resolved?

**Comment by cosmo0920** [comment]
I've released the patch for fixing this issue as v0.9.0.
Could you check it?
