### ISSUE TITLE
in_cloudwatch dublicates logs

### ISSUE THREAD

**Issue by bizzelicious** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#52]
Hi,

I use cloudwatch_in to fetch logs from cloudwatch logs and send those to elasticsearch. But it seems like I get dublicated entries in elasticsearch. As you can see I have several logs with the same (uniq) id and with the same timestamp. If I look in cloudwatch there is only one entry per id.
![dublicated logs es](https://cloud.githubusercontent.com/assets/13730491/17736344/927b62f2-6487-11e6-99f5-c6a561ec8bff.png)

It seems that I get more errors with a low fetch_interval but if I put it high (like 130sec) it still dublicate some logs.

**Comment by cosmo0920** [comment]
in_cloudwatch -> filter_elasticsearch_genid (bundled in ES plugin) -> out_elasticsearch -> Elasticsearch can solve this issue.

Elasticsearch reject to insert same IDs in `_id` fields.

```aconf
<source>
  @type cloudwatch_logs
  # ...
  @label @CLOUDWATCH
</source>
<@label @choplin CLOUDWATCH>
  <filter **>
    @type elasticsearch_genid
  </filter>
  <match **>
    @type elasticsearch
    id_key _hash
    # ...
  </match>
</label>
```
