### ISSUE TITLE
Merging of outstanding pull requests

### ISSUE THREAD

**Issue by sampointer** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#57]
I'm currently maintaining a fork of this repository with a selection of the outstanding PRs merged in. It would be greate to re-adopt upstream.

Any chance the outstanding PRs could be merged?

**Comment by sampointer** [comment]
@ryotarai bump

**Comment by sampointer** [comment]
@ryotarai Is there anything I can do to help you get the outstanding PRs merged?

**Comment by sampointer** [comment]
In frustration I've created: https://github.com/sampointer/fluent-plugin-cloudwatch-ingest

It addresses most of the issues I've been struggling to get merged (both my PRs and others)

**Comment by cosmo0920** [comment]
@sampointer Is this issue still active?

**Comment by cosmo0920** [comment]
fluent-plugin-cloudwatch-logs is maintained under fluent-plugins-nursery. This project is not "inactive".
Closing.
