### ISSUE TITLE
[QUESTION] Sourcing AWS Credentials

### ISSUE THREAD

**Issue by pantocrator27** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#72]
Can this plugin source credentials using the EC2 metadata service if there is an IAM role attached to an EC2 instance from which this is running?

**Comment by ndench** [comment]
This is an old issue, but for anyone coming from Google like me see #41.

**Comment by cosmo0920** [comment]
This issue seems old. Closing.
Delegate to #41.
