### ISSUE TITLE
How to set flush interval?

### ISSUE THREAD

**Issue by zhaoyao91** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#86]
I found it's not quick enough to see logs in cloudwatch. how to set flush interval?

**Comment by ndench** [comment]
@zhaoyao91 I know it's been a while, but did you ever find a way to set the interval?

**Comment by ndench** [comment]
I found that you can set `flush_interval` on any output buffer in fluentd: https://docs.fluentd.org/v1.0/articles/output-plugin-overview#buffering/retrying-parameters

example:

```
<match *>
    ...
    <store>
        ...
        flush_interval 10s
    </store>
</match>
```

**Comment by jglick** [comment]
Akin to https://github.com/uken/fluent-plugin-elasticsearch/issues/348?

**Comment by ndench** [comment]
Yes, it's no the plugin that has to support `flush_interval` and `flush_mode`, that is handled by fluntd.

**Comment by cosmo0920** [comment]
The solution is https://github.com/fluent-plugins-nursery/fluent-plugin-cloudwatch-logs/issues/86#issuecomment-398275619.

Yep, it is similar to  https://github.com/uken/fluent-plugin-elasticsearch/issues/348.
