### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by mamoroom** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#97]
Hi.
I really want to use env variables which is the default function of td-agent2 like bellow.

```
<match api.error>
  type cloudwatch_logs
  log_group_name "#{ENV['TD_AGENT_NAME']}/log"
  log_stream_name %{hostname}/api.error
  auto_create_stream true
  message_keys time,json
  flush_interval 5
</match>
```
https://docs.fluentd.org/v0.12/articles/faq#how-can-i-use-environment-variables-to-configure-parameters-dynamically?

It does't work for my enviroment.
- Ubuntu
- 16.04.2 LTS (Xenial Xerus)
- ruby 2.1.10p492 (2016-04-01 revision 54464) [x86_64-linux]
- td-agent 0.12.40

Let me know how to solve it.

Cheers.

**Comment by cosmo0920** [comment]
Could you show me boot log? Thanks.

**Comment by cosmo0920** [comment]
td-agent 2's init.d uses `/etc/default/td-agent` to override environment variables.

/etc/default/td-agent:
```
TD_AGENT_NAME=custom-td-agent-name
```

can set up `TD_AGENT_NAME`.
