### ISSUE TITLE
EC2 Instance Roles for out_cloudwatch

### ISSUE THREAD

**Issue by josagonzalez** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#99]
I would like to avoid creating a user account for the sole purpose of allowing fluentd to put logs in cloud watch. Is there a way to use EC2 instance roles to put the data in cloudwatch? Everything I've seen only allows me to export the access key/secret variables for the user

**Comment by josagonzalez** [comment]
After some more research, I found this issue: https://github.com/ryotarai/fluent-plugin-cloudwatch-logs/issues/68

It works fine if I give the instance the proper role with permissions, and I can push data up to cloudwatch without having a specific account associated with the fluentd service. 

I still have an open question: why does the policy require s3 GetObject permissions? What are those used for?

**Comment by m22r** [comment]
> I would like to avoid creating a user account for the sole purpose of allowing fluentd to put logs in cloud watch. Is there a way to use EC2 instance roles to put the data in cloudwatch? Everything I've seen only allows me to export the access key/secret variables for the user

@josagonzalez 
I could use EC2 instance profile to put data in cloudwatch.
my configs are below.

```
   <store>
     @type cloudwatch_logs
     region ap-northeast-1     # You must supply a region
     aws_instance_profile_credentials_retries 5    # default is nill 
     log_group_name my_log_group
     log_stream_name my_log_stream
     auto_create_stream true
     include_time_key true
     log_rejected_request true
     put_log_events_retry_wait 1s
     put_log_events_retry_limit 17
     json_handler json
   </store>
```

**Comment by cosmo0920** [comment]
https://github.com/fluent-plugins-nursery/fluent-plugin-cloudwatch-logs/issues/99#issuecomment-470846415 seems to be the solution. Closing.
